"""Subclass of FrameVolumes, which is generated by wxFormBuilder."""

import wx
import guiperfumes


# Implementing FrameVolumes
class FrameVolumes(guiperfumes.FrameVolumes):
    def __init__(self, parent):
        guiperfumes.FrameVolumes.__init__(self, parent)

    # Handlers for FrameVolumes events.
    def fecharFrame(self, event):
        self.Show(False)

    def adicionarVolume(self, event):
        # TODO: Implement adicionarVolume
        pass

    def atualizarVolume(self, event):
        # TODO: Implement atualizarVolume
        pass
