"""Subclass of FramePrincipal, which is generated by wxFormBuilder."""

import guiperfumes
from FrameMarca import FrameMarca
from FramePerfumes import FramePerfumes
from FrameVolumes import FrameVolumes


# Implementing FramePrincipal
class FramePrincipal(guiperfumes.FramePrincipal):
    def __init__(self, parent):
        guiperfumes.FramePrincipal.__init__(self, parent)
        self.frameMarca = None
        self.framePerfume = None

    # Handlers for FramePrincipal events.
    def fecharFramePrincipal(self, event):
        self.Destroy()

    def abrirMarca(self, event):

        if not self.frameMarca:
            self.FrameMarca = FrameMarca(self)
        self.FrameMarca.Show(True)

    def abrirFixacoes(self, event):
       pass

    def abrirVolumes(self, event):

        if not self.frameMarca:
            self.FrameVolumes = FrameVolumes(self)
        self.FrameVolumes.Show(True)


def abrirPerfume(self, event):
    if not self.framePerfume:
        self.framePerfume = FramePerfumes(self)
    self.framePerfume.Show(True)


def fecharApp(self, event):
    # TODO: Implement fecharApp

    pass
